### ISSUE TITLE
Finish and integrate teacher-card

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-client#100]
Finalizar e integrar la directiva teacher-card (commit: 2c58700603c0b32c7096911bd4c93792f859242a).

Tareas:
- Usar la directiva en las vistas correspondientes.
- Agregarle la lógica para el rating y las features de los profesores.

**Comment by nicogarcia** [comment]
No implementé la lógica del puntaje para que quede tres estrellas pintadas como ejemplo, ¿está bien?

**Comment by nicogarcia** [comment]
Implementado.
