### ISSUE TITLE
Preloader high cpu usage

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#106]
La compu se me traba un poco con el preloader (el circulito naranja de espera cuando verificas el mail) ¿Les pasa? @sergioam90 @federicojasson @tomasgil123

**Comment by federicojasson** [comment]
No me pasó. ¿A vos te pasó varias veces?
Si es realmente el preloader, esta página debería dejarte la máquina en coma: http://materializecss.com/preloader.html

**Comment by nicogarcia** [comment]
Es exactamente lo que pasa. Me pasa a mí nomas parece.

**Comment by federicojasson** [comment]
Si sos buena gente, podés abrirles un issue:
https://github.com/Dogfalo/materialize/issues

Jajaja

**Comment by nicogarcia** [comment]
Es muy probable que sea problema de mi máquina con los gráficos. Soy buena gente igual jaja 
:stuck_out_tongue:
