### ISSUE TITLE
Improve design of email verification screen

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#108]
Es este archivo:
app/scripts/presentation/account/signup/callback/local/local-user.verification.html

**Comment by tomasgil123** [comment]
Este es el issue para mejorar el diseño del mail de validacion que reciben aquellas prsonas que decidan registrarse con mail.

**Comment by sergioam90** [comment]
Tenes algun texto para poner, mono?

**Comment by nicogarcia** [comment]
Para redactar los textos tengan en cuenta que va a haber un link al proveedor de mail (lo hizo fede). Si es un Gmail va a haber un link a Gmail, y asi para varios.

**Comment by tomasgil123** [comment]
![validacion mail 1](https://cloud.githubusercontent.com/assets/14185059/10154238/68b947b8-663b-11e5-8126-faa06fb64178.png)

**Comment by tomasgil123** [comment]
![validacion mail 2](https://cloud.githubusercontent.com/assets/14185059/10154251/83f1cd2a-663b-11e5-8a84-3d29cbfdbcd3.png)

**Comment by tomasgil123** [comment]
Ademas hay que pensar el diseño y el texto de esas pantallas

**Comment by sergioam90** [comment]
Pero no serian esas las pantallas a hacer? Siempre supuse que eran esas nomas, ademas del email que le llega a la gente para validar

**Comment by nicogarcia** [comment]
Lo del mail q le llega al User esta en otro lado, este es el de la pantalla que dice Sergio

**Comment by sergioam90** [comment]
Faltaria el texto
![123123](https://cloud.githubusercontent.com/assets/13783674/10155163/80711578-6647-11e5-916c-8fcd634c9b4f.jpg)

**Comment by tomasgil123** [comment]
En la segunda pantalla, la que dice "estamos verificando tu email... danos unos segundos", cuando termina de cargar cambia el texto o que es bien lo que pasa? como se da cuenta el tipo de que la cuenta ya fue verificada?

**Comment by tomasgil123** [comment]
Para la primer pantalla podemos centrar el texto y poner esto:
"Te enviamos un email para verificar tu cuenta. Ahora seguí los siguientes pasos:
1- Revisa tu casilla de email
2- Busca y abrí el mail que te mandamos (a veces aparece como spam)
3- Hace click en “confirmar mail”
4- Volve a esta pestaña
Para ir a tu casilla de email hacé click acá
¡Te esperamos!"

**Comment by tomasgil123** [comment]
Para la segunda pantalla podemos centrar el texto y poner esto:

"Estamos verificando tu cuenta de mail… danos unos segundos"

Una vez que terminamos de verificar su cuenta le decimos:

"Listo! Ahora podes volver a la pestaña anterior y seguir con el proceso de registración!
(si la cerraste, hace click aca)"

"Listo! Ahora volve a la pestaña anterior!
(si la cerraste hace click aca)"

**Comment by sergioam90** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10175305/82d9754e-66c4-11e5-9ee0-dbf42de9eabe.jpg)

**Comment by nicogarcia** [comment]
Joya!

**Comment by sergioam90** [comment]
Ya esta todo, cierro este issue
