### ISSUE TITLE
Improve design of facebook data download screen

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#109]
Es este archivo:
app/scripts/presentation/account/signup/callback/facebook/signup.facebook.html

**Comment by tomasgil123** [comment]
Esto nico te referis la pantalla que te aprece despues de apretar el boton de "registrarme con facebook" y que dice "estamos descargando tus datos de facebook" o algo asi?

**Comment by nicogarcia** [comment]
Claro, hoy vimos que tardaba, así que se le puede agregar algo para que sea más agradable la espera también.

**Comment by sergioam90** [comment]
Se te ocurre que poner, mono?

**Comment by tomasgil123** [comment]
Les parece poner algo asi, poniendo la primera oracion mas visible y la segunda mas chiquita abajo:
"Facebook nos está confirmando tu cuenta.
En unos segundos vas a poder seguir con el proceso de registración"

**Comment by nicogarcia** [comment]
Acá les falta información nuestra: En este paso se bajan los datos de Facebook (nombre, fecha, email, foto (y la guardamos nosotros)) , no se confirma nada.

**Comment by tomasgil123** [comment]
Puse lo de "Facebook nos está confirmando tu cuenta" solo porque me parece que suena mejor que decirle que le estamos sacando o bajando datos de la cuenta jaj. Para mi la gente se queda mas tranquila leyendo lo primero que si le explicas lo que de verdad estas haciendo.

**Comment by nicogarcia** [comment]
Jaja "códigos web"! Lo va a ver en el siguiente paso que le sacaste datos, hay que ponerlo. Aclará que los datos los sacamos y no los guardamos si no los confirma si querés.

**Comment by tomasgil123** [comment]
Esta es otra opcion, poniendo la primera oracion mas visible y las otras dos mas chiquitas abajo: 
Facebook nos está mandando datos de tu cuenta para completar tu perfil en Upclaz
En unos segundos vas a poder seguir con el proceso de registración
(solo nos manda tu mail, nombre fecha de nacimiento y foto de perfil)

**Comment by sergioam90** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10174466/48fa5590-66c0-11e5-83b5-215c09f83996.jpg)

**Comment by nicogarcia** [comment]
Bien! Solo falta género en los datos

**Comment by sergioam90** [comment]
Listo
