### ISSUE TITLE
Design terminos y condiciones page and add to footer

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#110]
Ya estan redactados y chequeados

**Comment by sergioam90** [comment]
Pone el link acá si podes, del gdoc

**Comment by tomasgil123** [comment]
https://docs.google.com/document/d/193mX2hehaCBqPJjn7oS0G39YgbcixfeZkUVd2tz5GYk/edit

**Comment by sergioam90** [comment]
Ya está. Miralo cuando Nico lo suba.
