### ISSUE TITLE
Adjustment registration social networks step terminos y condiciones

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#111]
Agregarlo como en git hub "By clicking on "Create an account" below, you are agreeing to the Terms of Service and the Privacy Policy". Pone texto y te pone el link a los terminos y condiciones.
En nuestro caso quedaria "Haciendo click en culquiera de las tres opciones de registracion anteriores, estas aceptando nuestros terminos y condiciones"

**Comment by sergioam90** [comment]
Ya está. Miralo cuando Nico lo suba.
