### ISSUE TITLE
Adjustments to early adopter registration process

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#114]
Paso pagina perfiles: 
- Hacer que los dos perfiles que se muestren correspondan a la misma persona
- Agregar un titulo

Paso registracion redes sociales:
- Agregar lo de terminos y condiciones https://github.com/nicogarcia/classes-web-client/issues/111 
- Cambiar la frase que une las dos formas de registrarse de "o completando todos tus datos" a "o tambien podes usar, pero vas a tardar mas"

Paso tus clases:
- Agregar un tooltip para la pregunta "Cual es la direccion del lugar donde das clases particulares?" que diga "Tu direccion exacta no sera mostrada, solo sera utilizada para calcular la distancia entre el lugar donde das clases y la casa del alumno"
- Agregar check box "Si" y "No" a la paregunta "Das tambien clases a domicilio?"

Paso contacto:
- Agregar check box "Si" y "No" a las paregunta "Recibis mensajes de texto de tus alumnos?" y "Recibis mensajes de whatsapp?"

**Comment by tomasgil123** [comment]
@sergioam90 @nicogarcia

**Comment by tomasgil123** [comment]
- Paso servicios extra: Cambiar frase pantalla servicios extra: https://docs.google.com/document/d/1Am5t3acEsqDFAqh95fHaTvLbNGKlaxEnkQyEsz-Ktys/edit

**Comment by sergioam90** [comment]
- En cuanto a la frase en el paso del registro con redes sociales, me gusta más la que esta ahora.
- No funciona el botón para registrarme con google+
- Falta la sección donde cargas tu foto

Diseño: 
- Hay un error de diseño, le agregaría un poco de padding derecho al lado de cada texto "mañana, tarde, noche" etc. Quedan pegados al cuadro de selección de la "opción siguiente".
- El icono "$" esta desalineado con la caja a completar el valor

Cuando cree el usuario con facebook todo bien, pero cuando lo quise crear con mi email (otro email) de forma manual, me tiro un error

**Comment by nicogarcia** [comment]
Vamos a organizarnos mejor;
- Pongamos issues separados con tag "testing"
- Para lo de los checks y lo de google+ ya estan hechos los issues.
- Lo de cargar la foto lo esta haciendo fede (creo que tmb hay un issue).
- Para los detalles mínimos de diseño abran issues con tag "testing" y "minor".
- Cuando te tira un error abrí un issue describiendo bien lo que paso y copiando y pegando los datos de la consola de javascript.
