### ISSUE TITLE
Adjustment tus materias step selector

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#121]
No es posible buscar las materias segun su nivel asociado. Por ejemplo, "quimica secundario" no devuelve ningun resultado. Es posible que cambiar esto, para que cuando alguien ponga una materia acompañada de su nivel obtenga como resultado todas las materias con ese nombre (o pertenecientes a ese grupo, como en el caso de "quimica", "matematica", etc)?
Si es complicado, se pone un texto explicativo para facilitarle la busqueda a aquellos que quieran dar materias de secundario.

**Comment by tomasgil123** [comment]
Por el momento, vamos a poner un texto entonces. El texto diria lo siguiente "Las materias de nivel terciario, secundario o primario siempre se muestran al final de la lista"

**Comment by nicogarcia** [comment]
Hablé con fede y vuelven los checkbox, así que con eso se solucionaría.

**Comment by tomasgil123** [comment]
Ah buenisimo

**Comment by tomasgil123** [comment]
@federicojasson fede, cuando lo tengas listo, mandame una imagen de los check box asi lo puedo incluir como pregunta en el usability test. La idea es saber si les fue de alguna utilidad o no.

**Comment by federicojasson** [comment]
No sé si ya lo viste en la página, te lo dejo por si las moscas:

![image](https://cloud.githubusercontent.com/assets/3299231/10236561/50ff6fe6-687d-11e5-9956-da57122c27df.png)

**Comment by nicogarcia** [comment]
No le veo mucho sentido a esa búsqueda, creo que como esta es suficiente para este milestone. Si es necesario se abre para el siguiente.
