### ISSUE TITLE
Adjustment modalidad de tus clases step adress

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#122]
Agregar un tooltip a la pregunta "Cual es la direccion del lugar donde das clases particulares?" que diga "Tu direccion exacta no sera mostrada, solo sera utilizada para calcular la distancia entre el lugar donde das clases y la casa del alumno"

**Comment by nicogarcia** [comment]
No se si tenes claro que tooltip es esto: 
![image](https://cloud.githubusercontent.com/assets/241306/10147193/e05afb74-6602-11e5-9687-54364f0eef69.png)
Me parece que sería mejor poner directamente un texto con color secundario (gris).
@tomasgil123 Acordate de poner los textos siempre con ortografía perfecta, sino es un trabajito extra a la hora de ponerlo

**Comment by tomasgil123** [comment]
Sisi, sabia. Me lo habia imaginado como un icono con un signo de pregunta, que vos al pasar el cursor por arriba pudieses leer ese texto. Si es mas facil poner el texto abajo de la pregunta en otro color, hagamos eso! Voy a aprender a escribir bien con ustedes :P jaj

**Comment by nicogarcia** [comment]
Ah, esta bien. Es más facil lo del texto por ahora, lo hacemos así.
¡Jaja! Nos van a mandar a particular de lengua sino los pibes.
