### ISSUE TITLE
Adjustment modalidad de tus clases step horarios

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#126]
Colocar debajo de cada texto "Mañana", "tarde", "noche" los horarios asociados a cada concepto. Mañana 8-13 hs, Tarde 13-18hs hs, Noche 18 - hs

**Comment by nicogarcia** [comment]
Esto es lo mejor que se puede hacer para este milestone.
![image](https://cloud.githubusercontent.com/assets/241306/10197158/a6281e26-676c-11e5-840b-9de29bf0f542.png)

**Comment by tomasgil123** [comment]
Por mas que no quede bien visualmente, yo incorporaria los horarios al lado de cada check box. @sergioam90

**Comment by nicogarcia** [comment]
Así queda:

![image](https://cloud.githubusercontent.com/assets/241306/10197824/c5d47ca8-676f-11e5-96ea-db5f319847f4.png)

Si separamos los checks, el ultimo se cae al otro renglón, igual que si la pantalla es mas chica. ¿Es necesario contaminar así los checks? Sigo en desacuerdo, se podría agregar un mensaje que diga que se considera "tarde" hasta las 18 y listo, de última. 
Es un dato difuso (que habría que meterlo también en los filtros cosa que es imposible), es obvio para "mañana" y "tarde", y después va a desaparecer.

**Comment by nicogarcia** [comment]
O ponerle la hora solo a "Tarde"

**Comment by tomasgil123** [comment]
Propuesta, y si sacamos las palabras "mañana", "tarde" y "noche" y dejamos solo los horarios? La verdad que son conceptos difusos y que su significado va cambiando segun la etapa del año en la que estamos. El objetivo ultimo de poner "horarios" es que los pibes puedan identificar de manera facil y rapida los profesores que dan clases en los horarios que ellos tienen disponibles.

**Comment by nicogarcia** [comment]
Complica todo hacer eso. Los filtros dejan de ser simples. No se puede plasmar la disponibilidad del profesor fácilmente, si el tipo se quiere cubrir pone los tres y listo, sino inducimos a error porque la búsqueda no considera horarios fijos.
En sí ya los horarios son difusos, entonces poner una representación difusa me parece la mejor opción.
Por todos los ejemplos que ya dijimos, si el tipo da de 17 a 19, es la tarde aunque sea después de las 18. Hay que interpretarlo como lo que es, es un hint, una ayuda para el que busca, no es primordial, si fuera así hay que poner formato HH:mm para el filtro.
