### ISSUE TITLE
Adjustment contacto step radio buttons

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#127]
Agregar check box "Si" y "No" a las paregunta "Recibis mensajes de texto de tus alumnos?" y "Recibis mensajes de whatsapp?"

**Comment by tomasgil123** [comment]
@nicogarcia Nico, esta es la encuestita que hice. La respondieron 6 personas. Una la respondio mal y hubo gente que respondio que no es del todo facil darse cuenta que la forma de indicar "no" es sin hacer click. https://docs.google.com/forms/d/1nkxXpZx9iwTqHPHlfCve-Fb8FrjB6HOJc0mA9wsIMmo/edit Los radio buttons "Si" y "No" son mas feos, pero no dejan ninguna duda sobre como funcionan.

**Comment by nicogarcia** [comment]
Jaja que ladri esa encuesta
