### ISSUE TITLE
Adjustment contacto step mail

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#128]
Agregar pregunta "Recibis mails?" junto con check boxes con las opciones "Si" y "No" como respuestas.

**Comment by nicogarcia** [comment]
Esto es un dato relacionado al usuario que se debe almacenar, no es minor, diría que es complicado para agregarlo por el valor que parece tener.

**Comment by nicogarcia** [comment]
No parece tener demasiado sentido una comunicación offline para acordar una clase.
