### ISSUE TITLE
Adjustment servicios premium step text

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#129]
Cambiar la frase que acompaña la pantalla de servicios premium. Tres opciones:
- Te gustaria actualizar tu cuenta gratuita a alguna de estas dos opciones?
- Te gustaria agregar a tu cuenta gratuita alguna de estas funcionalidades?
- Te gustaria que tu cuenta sea solo gratuita o tambien queres tener alguna de estas funcionalidades extra?
https://docs.google.com/document/d/1Am5t3acEsqDFAqh95fHaTvLbNGKlaxEnkQyEsz-Ktys/edit

**Comment by sergioam90** [comment]
Ya está. Miralo cuando Nico lo suba.
