### ISSUE TITLE
Adjustment servicios premium step paid options

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#130]
Texto que va a aparecer cuando se haga click sobre alguno de los planes pagos:
- "Ups! Nos alegra saber que te gustaria poder dar turnos online, pero todavia no estamos del todo listos. Nuestros desarrolladores estan haciendo todo lo posible para terminar de implementarlos. Cuando el servicio este disponible te vamos a avisar!"

**Comment by tomasgil123** [comment]
Ups! Nos alegra saber que te gustaría poder dar turnos online, pero todavía no estamos del todo listos. Nuestros programadores están haciendo todo lo posible para terminar de implementarlos. Cuando el servicio esté disponible te vamos a avisar!

**Comment by nicogarcia** [comment]
Esta subido, quedo medio pelado y choto de leer, ¿ideas?

**Comment by nicogarcia** [comment]
![image](https://cloud.githubusercontent.com/assets/241306/10164846/4cec226a-6692-11e5-8a60-04c57105077c.png)

**Comment by nicogarcia** [comment]
Listo, ya se guarda en teacher.
