### ISSUE TITLE
Plan: to be saved in the server

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#131]
Cuando algun oferente hace click sobre alguna de las dos opciones pagas se le va a mostrar un mensaje como este "Ups! Nos alegra saber que te gustaria poder dar turnos online, pero todavia no estamos del todo listos. Nuestros desarrolladores estan haciendo todo lo posible para terminar de implementarlos. Cuando el servicio este disponible te vamos a avisar"
Es viable? @nicogarcia @federicojasson

**Comment by nicogarcia** [comment]
Totalmente

**Comment by nicogarcia** [comment]
@federicojasson Lo hicimos con analytics ahora, lo mandamos para el siguiente milestone?

**Comment by tomasgil123** [comment]
Si esto puede incluirse antes de largar, seria genial. Estaba pensando que saber quien hizo click en que boton va a ser importante para despues adptar la encuesta que se le haga.

**Comment by nicogarcia** [comment]
@federicojasson

**Comment by federicojasson** [comment]
Lo voy a hacer "mal y rápido" en dos patadas, con la esperanza de que no surgan más cosas de este tipo (en cuyo caso, habrá que pensarlo mejor y rehacerlo).

**Comment by federicojasson** [comment]
Server issue: nicogarcia/classes-web-server#51
