### ISSUE TITLE
Adjustment datos personales step image 

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#133]
Todavia no puede cargarse una imagen cuando te registras. @federicojasson

**Comment by federicojasson** [comment]
¿Cierro?

**Comment by nicogarcia** [comment]
No, falta integrar y que funcione la subida.

**Comment by federicojasson** [comment]
¿Y #48 ?

**Comment by nicogarcia** [comment]
Jaja entonces es un duplicado
