### ISSUE TITLE
Email validation error

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#136]
Subo los correspondientes screenshots. Son tres errores los que saltaron. Cualquier cosa pregunta @federicojasson 
![error me 1](https://cloud.githubusercontent.com/assets/14185059/10155096/a3fef3e4-6646-11e5-8c07-675d3f826845.png)
![error me 2](https://cloud.githubusercontent.com/assets/14185059/10155097/a435feca-6646-11e5-96ac-7db17cc8d75d.png)
![error me 3](https://cloud.githubusercontent.com/assets/14185059/10155098/a43801f2-6646-11e5-9811-ae5b9ddf74bc.png)

**Comment by tomasgil123** [comment]
![error verification 1](https://cloud.githubusercontent.com/assets/14185059/10155105/baf468cc-6646-11e5-8eab-694c1d389ca7.png)
![Uploading error verification 2.png…]()
![Uploading error verification 3.png…]()

**Comment by tomasgil123** [comment]
![error token 1](https://cloud.githubusercontent.com/assets/14185059/10155115/e11cedf8-6646-11e5-925c-fda7e4410efb.png)
![error token 2](https://cloud.githubusercontent.com/assets/14185059/10155116/e1203904-6646-11e5-907f-d402da0d7fc1.png)
![error token 3](https://cloud.githubusercontent.com/assets/14185059/10155117/e124a930-6646-11e5-89fe-59d29fa000b4.png)

**Comment by tomasgil123** [comment]
Hoy me volvio a pasar lo mismo.

**Comment by nicogarcia** [comment]
@federicojasson

**Comment by federicojasson** [comment]
Viendo esto parece un problema de cliente.
Necesitaríamos un poco de contexto para entender el problema. ¿En qué momento ocurrió esto?

**Comment by federicojasson** [comment]
Probablemente no sea nada. Usamos el storage del navegador para guardar los tokens, y al reiniciar el servidor seguramente intenta conectarse con ese token (que ya no es válido).

Prueba para la próxima vez que pase: ¿si hacés logout y volvés a loguearte se arregla? @tomasgil123

**Comment by federicojasson** [comment]
@nicogarcia ¿Tal vez habría que implementar un logout automático en caso de que ocurra algo así?

**Comment by nicogarcia** [comment]
Debería estar solucionado, si vuelve a fallar, reabran.
