### ISSUE TITLE
Change text of paid options

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#137]
"Nicho de oferta y demanda de clases particulares" 
Me parece que la mayoría de la gente no lo entiende.

**Comment by tomasgil123** [comment]
No puedo encontrar la imagen con el resto de los planes y su descripcion. Por ahi podemos poner algo que contraste con lo prometido en las opciones pagas. Por ejemplo "Tus alumnos reservan turnos con vos llamandote o por SMS"

**Comment by nicogarcia** [comment]
"Tus alumnos podrán reservar clases comunicándose directamente con vos"

**Comment by tomasgil123** [comment]
Me parece bien!
