### ISSUE TITLE
Upload upclaz icons to Google Drive folder and put link here

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#138]
Es para tenerlos para la cuenta de gmail, la app de facebook, google+ etc.

**Comment by sergioam90** [comment]
https://drive.google.com/open?id=0B-4mXWk7uagJenBZYUFTQlh4S1k

**Comment by nicogarcia** [comment]
Subilos listos para poner como icono, uno solo por imagen. El posta, ¿no es el naranja con blanco sin Upclaz.com? (con upclaz.com se usa también)

**Comment by sergioam90** [comment]
y en que tamaño? Supongo que dependiendo donde lo vayas a usar el tamaño cambia, por eso subi el archivo directamente con todas las formas

**Comment by sergioam90** [comment]
Listo

https://drive.google.com/drive/u/0/folders/0B-4mXWk7uagJenBZYUFTQlh4S1k
