### ISSUE TITLE
Landing page and faq adjustment

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#139]
Me recomendaron no poner "conseguir mas alumnos" como uno de los beneficios porque puede ser considerado como publicidad engañosa por los oferentes que no consigan nuevos alumnos (seguramente van a existir). Habria que cambiarlo de la faq tmb. La nueva frase seria "Llega a mas alumnos".

**Comment by tomasgil123** [comment]
Lo que se me ocurre para que no se repita la palabra "llegar" es cambiar la frase "Llegá a nuevos estudiantes de todos los niveles de manera más fácil" por "Conectate con nuevos estudiantes de todos los niveles que buscan un profesor como vos".

**Comment by sergioam90** [comment]
Justo la cambie, por "Ofrecé tus servicios a nuevos estudiantes de todos los niveles de manera más fácil."

**Comment by tomasgil123** [comment]
Buenisimo. Me gusta esa frase tambien.

**Comment by sergioam90** [comment]
Listo entonces
