### ISSUE TITLE
Add new subject tus materias step

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#140]
Existe la posibilidad de que el profesor de particular no pueda encontrar la materia que quiera dar. Se puede poner un texto abajo de la pregunta que diga "No pudiste encontrar la materia que queres dar? envianos un mail a esta casilla ... con su nombre para que la agreguemos"

**Comment by nicogarcia** [comment]
¿Cómo es la comunicación? 
Podríamos poner según como se registro:
Face => Facebook Message
Google => Google Plus
Local => Email

**Comment by nicogarcia** [comment]
@sergioam90 @tomasgil123

**Comment by tomasgil123** [comment]
Si bien es algo importante facilitarle el envio de feedback al oferente con respecto al tema de las materias, yo priorizaria largar. Por el momento haria lo que sea mas facil, que me parece que es poner esa frase, el mail y un link a nuestra pagina de face, independientemente de como se haya registrado. De ultima, se puede tambien poner un link que lo lleve a su casilla de correo, para facilitarle el proceso. Mas adelante, incorporaria un software de customer service como este https://chatra.io/#features
