### ISSUE TITLE
Continue with registration email verification screen is closed

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#141]
Si el oferente que esta completando el proceso de registracion cierra por equivocacion la primera pantalla, tiene que poder seguir el proceso de registracion desde la segunda. 
![validacion mail 1](https://cloud.githubusercontent.com/assets/14185059/10171959/12a7252a-66b3-11e5-8593-c98982efe9c8.png)
![validacion mail 2](https://cloud.githubusercontent.com/assets/14185059/10171960/12a7d20e-66b3-11e5-81d1-20851851b96c.png)

**Comment by nicogarcia** [comment]
Done
