### ISSUE TITLE
error facebook sign up

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#142]
![error sign up facebook 1](https://cloud.githubusercontent.com/assets/14185059/10177306/dff9e7da-66cf-11e5-8df1-62b9c7648e04.png)
![error sign up facebook 2](https://cloud.githubusercontent.com/assets/14185059/10177307/dffa0abc-66cf-11e5-9899-4d226e044904.png)

**Comment by nicogarcia** [comment]
@federicojasson

**Comment by federicojasson** [comment]
Los mensajes de error de las redes sociales son enviadas al cliente directamente (el server no los modifica):

https://github.com/nicogarcia/classes-web-server/blob/master/src/main/java/com/classes/app/core/security/HttpStatusCodeExceptionHandler.java

Acabo de agregar un println (417ecffc9e8fe82a11d94cea7b78d9afcafd5e63) para que muestre detalles la próxima vez que ocurra.
Pero estoy casi seguro que es problema de Facebook en todo caso.

**Comment by federicojasson** [comment]
Por cierto, este issue debería estar en el repositorio del server me parece.

**Comment by nicogarcia** [comment]
Cerramos por ahora.
