### ISSUE TITLE
Add action if email verification code is already used

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#144]

**Comment by nicogarcia** [comment]
¿Qué opciones deberíamos ofrecer? @federicojasson

**Comment by federicojasson** [comment]
"email code"?

**Comment by nicogarcia** [comment]
¿Ahora? (¡un poquito de imaginación!)

**Comment by federicojasson** [comment]
Otra cosa que me dificultó la comprensión fue lo de "is already used" en vez de "has already been used" jaja

Yo pondría una pantalla de que "ya no es válido". Otra cosa que tenés que chequear cuando hacés ese pedido es que puede retornar 404 (Not Found). Esto ocurriría cuando el usuario es eliminado automáticamente por no verificar su email (tiene 2 días para hacerlo). En ese caso podría ponerse una explicación más detallada (de que tiene que registrarse de vuelta, etc).
