### ISSUE TITLE
Reduce about page height to fit in window

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#146]
Es muy molesto que el siguiente no se vea en la página, hay que resumirla más o achicar las imágenes.
También hay que poner un título.

**Comment by nicogarcia** [comment]
Cambiar "Cuando mas información" a "Cuanta más información"

**Comment by nicogarcia** [comment]
Se podrían poner las imágenes con sus respectivos títulos arriba y ocupar el espacio que ocupa una sola como esta ahora.

**Comment by nicogarcia** [comment]
@tomasgil123

**Comment by tomasgil123** [comment]
Si, se va a ver un poco peor, pero que el siguiente este a la vista es importante.

**Comment by sergioam90** [comment]
Si mantenes el tamaño del texto no creo que te entre igual en una pantalla, pero si queres, proba. 

Claramente lo ideal seria que no tenga que hacer scroll.
