### ISSUE TITLE
Mail / Género --> Email / Sexo

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-client#150]
https://github.com/nicogarcia/classes-web-client/search?utf8=%E2%9C%93&q=g%C3%A9nero&type=Code
Cambiaría "género" por "sexo"

https://github.com/nicogarcia/classes-web-client/search?utf8=%E2%9C%93&q=mail&type=Code
Cambiaría "mail" por "email" (esto último por consistencia)

**Comment by nicogarcia** [comment]
Lo de sexo no se, no me parece.

**Comment by federicojasson** [comment]
¿Tenés dudas de la palabra? Te dejo un ejemplo de unos que no saben nada (?)

![image](https://cloud.githubusercontent.com/assets/3299231/10236752/0fcee6b6-6880-11e5-91bb-2ec9d7872f63.png)

**Comment by tomasgil123** [comment]
Pese a todo, a mi me parece que queda mejor "genero", aunque no pude encontrar ninguna pagina como ejemplo :P
