### ISSUE TITLE
Make and apply analytics event naming convention

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#151]

**Comment by tomasgil123** [comment]
Lo que hay que medir con analytics es:
- Time in page (el tiempo promedio que pasan los usuarios en cada pagina)
- Pagina de abandono (la pagina en la que la gente se va)

Lo de los cliks de los botones de los planes se hace desde el servidor asique para eso no necesitariamos usar analytics.
La idea es detectar que partes del proceso de registracion les llevan mas tiempo a la gente y en que parte del proceso abandonan. En base a esa info, realizar cambios en el proceso de registracion.
Sergio, se te ocurre algo mas? @sergioam90

**Comment by sergioam90** [comment]
No se como funcionara Analytics con esto de Angular, pero lo que pusiste se puede medir facilmente.

Un tip: Hay una opción para que todos pongamos nuestra ip y esta no cuente en la medición, que nos excluya. Para no cagar las estadísticas cada vez que entramos, por lo menos desde nuestra casa.

Van a ser pocas visitas en esta primera semana con los early adopters solos, pero creo que tiene que funcionar igual.

Me parece que nada mas.

**Comment by nicogarcia** [comment]
En Angular es equivalente a lo tradicional, cada cambio de vista se cuenta como una "pagina".

Además se pueden agregar eventos como por ejemplo: signup-local_funny-modal__liked que lo puse para medir que tanto le gusta a la gente ese detalle.

A ese tipo de cosas me refería, pero si con las vistas es suficiente, estamos bien así.

**Comment by tomasgil123** [comment]
Si, por el momento no hay que medir muchas cosas. Esta bueno lo que dice sergio, habria que hacerlo.

**Comment by nicogarcia** [comment]
No son estáticas las IP, no creo que distorsionemos las mediciones. @federicojasson ?

**Comment by federicojasson** [comment]
Creo que cambian cada vez que se reinicia el módem. Por ejemplo, recién se me cortó la luz, tal vez tengo otra IP.

**Comment by nicogarcia** [comment]
Claro, por eso, no creo que valga la pena mantener eso.
