### ISSUE TITLE
Add loading status to confirm button in crop-modal

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#157]
El loading se usa así:

        <a class="btn"
           loading-link // Habilita la directiva
           loading-spinner  // Habilita el spinner en el botón
           loading-promise="vm.promise" // Promesa a la que se "espera"
           loading-text="Creando..." // Mensaje de carga
           loading-always-restore // Habilita el reestablecimiento del botón a su contenido inicial
           ng-click="vm.goToNextStep()">
            Siguiente
        </a>

Si no se habilita el loading-always-resotore vuelve a su estado inicial sólo en caso de error.

**Comment by federicojasson** [comment]
La directiva loading-link no desactiva el ng-click. ¿No debería?

**Comment by nicogarcia** [comment]
You're right!

**Comment by federicojasson** [comment]
Lo probé. Si me das el OK la modifico.

**Comment by nicogarcia** [comment]
"OK" :stuck_out_tongue:
