### ISSUE TITLE
Testing results 3-oct

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#162]
### Test 1: Mujer (55)
- No entiende el datepicker

### Test 2: Hombre (53)
- Abre el mail en el celular y se arrepiente. No puede continuar en la PC.
- No encuentra donde escribir la dirección, se confunde con el label de "Calle" y "Ciudad"
- Comete ese error y apreta siguiente sin notar que cometió un error, no sabe como seguir.
- No le gusta la sorpresa

### Test 3: Hombre (22)
- Intenta abrir el mail desde el celular y se le indica que no lo haga por el error en el test anterior.
- No entiende el datepicker
- No advirtió la sorpresa
- Comprende la selección de materias sin los filtros (se los eliminé de la página)

### Resultados
- Nadie entiende la selección de materias con los filtros. Test 3 lo entiende si son removidos. (#159)
- Agregar posibilidad de loguearse desde la PC cuando se abrió el link del mail en el celular.(#160)
- Agregar mensaje descriptivo al datepicker y volver a testear. (#158)
- Mejorar descripción de "Calle y Ciudad" (#161)
- Mejorar el texto del plan plus (#163)

**Comment by nicogarcia** [comment]
@tomasgil123

**Comment by tomasgil123** [comment]
Test 4: mujer (25)  Registracion con mail
- No entiende la forma en que la pagina le podria conseguir nuevos alumnos a un profesor de particular.
- No subio foto
- Indiferente entre seguir con el proceso de registracion despues de validar su mail en una nueva ventana o en la anterior.
- No entendio la diferencia entre nivel academico y extracurricular.
- No uso los chck box.
- Le resulto complicado poner la direccion.
- No entedio el ultimo plan

Test 5: Hombre (27)  Registracion con mail
- No entiende la forma en que la pagina le podria conseguir nuevos alumnos a un profesor de particular.
- No subio foto.
- Indiferente entre seguir con el proceso de registracion despues de validar su mail en una nueva ventana o en la anterior.
- No utilizo el buscador de materias. Comenzo diferectamente a seleccionar las materias de la lista.
- No se dio cuenta de que la tarjeta de profesor que se muestra era la de el y que se iba llenando.
- No entendio el ultimo plan.

Resultados:
- Modificar el lugar de donde se encuentra la opcion para subir la imagen. Change place image upload #168 
- Modificar la landing page para dejar en claro como Upclaz les va a permitir a los profesores particulares conseguir nuevos alumnos.https://github.com/nicogarcia/classes-web-client/issues/167
