### ISSUE TITLE
Improve plus plan description

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#163]

**Comment by nicogarcia** [comment]
@tomasgil123

**Comment by nicogarcia** [comment]
@tomasgil123

**Comment by tomasgil123** [comment]
En lugar de "gestiona mejor tus descuentos por clases grupales y cantidad de horas" poner:

"Ofrece de manera mas facil tus descuentos por clases grupales y cantidad de horas"

"Llega a mas alumnos con tus descuentos por clases grupales y cantidad de horas"

Por mas que la definicion siga siendo bastante vaga, me parece que aquellos profesores de particular que utilizan con frecuencia estrategias de promocion basadas en descuentos, se va a mostrar interesado. Con solo identificar esas personas, ya es un monton.

**Comment by nicogarcia** [comment]
¿Te gusta esta? Es más concreta y más parecida a las de los otros planes.
"Tus alumnos pueden obtener descuentos grupales.
Tus alumnos pueden reservar múltiples clases."

**Comment by tomasgil123** [comment]
Me gusta. La idea seria ponerlo en dos renglones, no? Agregaria al segundo beneficio "tus alumnos pueden obtener descuentos reservando multiples clases"

**Comment by nicogarcia** [comment]
Claro

**Comment by nicogarcia** [comment]
![image](https://cloud.githubusercontent.com/assets/241306/10279924/e5bdcb90-6b3f-11e5-89a9-4a91c1c66c93.png)
