### ISSUE TITLE
Change degrees names

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#164]
En los test noté que en general no se entienden los nombres de nivel de estudios.

Sugerencia:
- Cambiar "Graduado" (suena nerd y yankee) a "Recibido"
  - No recibido
  - Recibido
  - "...." (acá no sé)

**Comment by nicogarcia** [comment]
@tomasgil123 @federicojasson @sergioam90

**Comment by tomasgil123** [comment]
No se me ocurre otra cosa que "superior a recibido" y en lugar de "no recibido" puede ponerse "estudiante"

**Comment by nicogarcia** [comment]
¿Coincidís con lo de recibido? ¿@sergioam90 @federicojasson?

**Comment by federicojasson** [comment]
No me parece mal, es más argento. El tema es qué poner en el postgraduate.

**Comment by nicogarcia** [comment]
¿Doctorado? "Doctorado o similar" ?
