### ISSUE TITLE
Change landing page early adopters

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#167]
A la gente no le queda del todo claro como vamos a cumplir con nuestra promesa de "llegar a mas alumnos". 
Solucion: incorporar un paso al como funciona que diga "Upclaz.com sera promocionada por diferentes medios, para que se haga conocida y tanto padres como alumnos comiencen a utilizarla"
La imagen que acompañaria este texto seria un megafono.

**Comment by sergioam90** [comment]
Queda bien asi?

![path12](https://cloud.githubusercontent.com/assets/13783674/10269383/8dcc29ec-6aac-11e5-8b56-e5ee76fff896.png)

**Comment by federicojasson** [comment]
Queda bien :+1:

**Comment by tomasgil123** [comment]
Opciones para el texto:

"Upclaz.com sera promocionada mediante una campaña de marketing integral, para que tanto padres como alumnos comiencen a utilizarla"

"Upclaz.com sera promocionada mediante una campaña de marketing offline y online, para que tanto padres como alumnos comiencen a utilizarla"

"Realizaremos una campaña de marketing integral para que tanto padres como alumnos comiencen a utilizarla"

**Comment by tomasgil123** [comment]
Trataria de mencionar al final de la frase que padres y alumnos la van a empezar a utilizar porque me parece que se relaciona con la frase de la portada "A partir de octubre, el lugar donde todos van a buscar su profesor de particular"

**Comment by sergioam90** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/13783674/10269644/afe93d24-6ab3-11e5-96ab-fe848278c95d.jpg)

**Comment by tomasgil123** [comment]
No hay chances de que se vea un poco mas la manija del megafono?

**Comment by sergioam90** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/13783674/10269682/687f99be-6ab4-11e5-9819-ae367c5ac3b1.jpg)

**Comment by tomasgil123** [comment]
Me parece que queda mejor asi!

**Comment by nicogarcia** [comment]
¿Campaña de marketing? ¿Qué es eso? ¿Sabe la gente que significa?

**Comment by sergioam90** [comment]
La gente puede no saber especificamente que es, pero sabe que es lo que se utiliza para dar a conocer los productos/servicios me parece.

Si miras la primera imagen, el texto que redacto el mono me pareció a mi particularmente bastante "vago", "light". Si estamos agregando un item porque la gente no entiende como vamos a conseguirles mas alumnos, hay que ser mas específicos. Creo que esa es la forma de convencer

**Comment by nicogarcia** [comment]
Yo sacaría campaña de marketing integral (cuando alguien lee eso, abandona probablemente).
"... será *promocionada en distintos medios* para que tanto padres..."

**Comment by sergioam90** [comment]
A mi no me convences con esa frase, es como la inicial que habia dicho el mono. Igualmente,  si a la mayoria le parece, lo ponemos de esa forma.

**Comment by tomasgil123** [comment]
No creo que la gente te pueda dar una definicion exacta de "campaña de marketing", pero creo que mas o menos entiende que es. Ademas, creo que tiene una connotacion mas profesional que decir solamente "sera promocionada en diferentes medios"

**Comment by nicogarcia** [comment]
Si es por el Look & Feel gana, pero creo que el problema era que no se entendía.

**Comment by sergioam90** [comment]
No es por el look, tiene que dejar conforme al oferente. Si por mas que no lo entienda del todo, queda conforme, alcanza.

Si le pones "será promocionada por diferentes medios" y no le termina de cerrar, no sirve.

**Comment by nicogarcia** [comment]
Vislumbro discusión eterna sin fundamentos claros xD Abandono. Si hay pruebas de que algo chamuyero y que el común de la gente no sabe que es, deja conforme al que lo lee, prosigan :smile:
