### ISSUE TITLE
Make personalized mails

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#219]
Crear mails de tomasgil@upclaz.com y sergiomagariños@upclaz.com . Desde el punto de vista de la persona que esta siendo contactada se percibe el contacto como mucho mas personalizado que si se le envia directamente desde un mail como contacto@upclaz.com
Te lo asigno a vos fede porque fuiste el que armo todo el tema de los mails.

**Comment by nicogarcia** [comment]
Acuérdense de la cuota de 300 mails diarios que hay para mandar como @upclaz.com.

**Comment by federicojasson** [comment]
:+1: Ahí me pongo
