### ISSUE TITLE
Implement ordering

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#32]
Directive should be horizontal, name next to icon

**Comment by nicogarcia** [comment]
First version:
![image](https://cloud.githubusercontent.com/assets/241306/9748893/7b2b8e5c-565e-11e5-8b3c-466cc15fe20a.png)
Tell me what you think and test it online. @tomasgil123 @sergioam90 @federicojasson

**Comment by federicojasson** [comment]
TODO:

- Use dollar sign for the fee filter
- Add a column for the direction arrow (to avoid filter icon from shifting)
- Add title "Ordenar" instead of repeating it in every row

**Comment by nicogarcia** [comment]
Wrong commit message, sorry.

**Comment by nicogarcia** [comment]
We have a problem with mobile and desktop view if we put filters and sorting in different rows. In mobile sorting will appear below the results. Should we duplicate code? Or can we change sort design to a wide bar over results (like the one with messages)? @tomasgil123 @sergioam90
