### ISSUE TITLE
Design login and signup flow, try to unify them as for social users

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#41]
Pasos:
0) Boton de registrarse (landing page)
1) Info sobre la pagina(titulo)
2) Registracion con redes sociales o con mail
3) Tus datos personales
4) Tus materias
5) Modalidad de tus clases
6) Tu info de contacto
7) Servicio premium

**Comment by tomasgil123** [comment]
Proceso de registracion:
-Boton de registrarse
-

**Comment by federicojasson** [comment]
Selección de materias:

Dado que el servidor acepta que no se indique ninguna materia (https://github.com/nicogarcia/classes-web-server/blob/master/src/main/java/com/classes/app/teacher/TeacherValidator.java#L15), podría indicarse algo así como: "No es necesario que seleccione las materias ahora, puede hacerlo después".

Alternativa: forzar a que se indique al menos una materia. @nicogarcia @tomasgil123 @sergioam90

**Comment by nicogarcia** [comment]
Y si dejamos que pueda no elegir nada? Acordate que habíamos quedado en no habilitar la **edicion** del perfil en la primer etapa, para simplificar.

**Comment by federicojasson** [comment]
Eso es lo que me hace dudar, si necesitamos que seleccione materias en el sign-up (dado que no va a poder editarlas después). Actualmente se deja no seleccionar nada, si nadie opina distinto lo dejamos así.

**Comment by tomasgil123** [comment]
Yo diria de hacerle creer al oferente que es un campo obligatorio, pese a que si no pone nada puede seguir con el proceso de registracion igual. Aparte, creo que ese es un dato que la gente no va a tener problema en dar. Una pregunta, vamos a poder hacer consultas en SQl a la base de datos de oferentes a medida que se vayan registrando?

**Comment by tomasgil123** [comment]
nombre y apellido son dos campos separados, no?

**Comment by federicojasson** [comment]
Dado que la ciudad es una propiedad específica del perfil de profesor/estudiante, no podemos obtener ese dato al momento de crear el usuario (la creación del perfil de profesor/estudiante es posterior a la obtención de esa información)

**Comment by tomasgil123** [comment]
Con respecto al paso final, el de los servicios premium, si puede identificarse la persona que hice click y la que no, mejor. No me acuerdo que habiamos terminado de decidir en casa

**Comment by nicogarcia** [comment]
Si, se va a poder. "Lugar donde vivis (esta info se saca del sign up con redes sociales tmb?)" esto esta en usuario, no se bien a que te referis, el profesor tiene dirección como profesor y como alumno (que pueden ser distintas), pero no en usuario.

**Comment by nicogarcia** [comment]
Falta la información de estudios del profesor.

**Comment by nicogarcia** [comment]
Antes que nada, excelente uso del markdown!! @tomasgil123
Pongo algunas cosas tachadas para que veamos los cambios (se hace con dos de estos "~").
Para la próxima, los textos que sean para copiar y pegar en la página ponelos con las tildes, los signos de puntuación y entre comillas ;)

**Comment by nicogarcia** [comment]
Voy a cambiar la info de usuario a preguntas.

**Comment by tomasgil123** [comment]
Fede, como te parece poner lo de las redes sociales?

**Comment by tomasgil123** [comment]
Fede, como te parece poner el texto sobre la registracion con las redes sociales?

**Comment by federicojasson** [comment]
¿Te referís a gráficamente? Te puedo hacer un diseño rápido si querés.

**Comment by tomasgil123** [comment]
nono, en el hangout creo que habias dicho que el texto no te gustaba. Esto "Registrarte con las redes sociales hace mas facil y rapido que te crees una cuenta, porque nos permite completar automaticamente parte de los datos que despues te vamos a pedir, como una foto para tu perfil de profesor, tu nombre y apellido o tu edad.
Que te registres con Face o Google no nos permite acceder a tus amigos o publicar desde tu cuenta. "

**Comment by tomasgil123** [comment]
Con respecto al tema de si el usuario oferente es un instituto o no, ahora dejemos las preguntas como estan (lo de poner "otro" como genero no lo hagan :P). Si descubrimos que los institutos son un segmento de usuarios especial y realmente tiene sentido que tengan un registro diferente, lo hacemos.

**Comment by federicojasson** [comment]
Coincido. Sin dudas los institutos van a requerir un manejo especial.

**Comment by sergioam90** [comment]
Necesitamos opiniones..

![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10023727/d3e4e194-6129-11e5-89bd-6707a31cb92b.jpg)

**Comment by nicogarcia** [comment]
Gráficamente:
- El estilo no me cierra, creo que tendría que ser sin borde y con sombra como las tarjetas.
- Le faltaría un fondo al titulo para que resalte más.
- Los títulos de los items deberían ir separados del texto (el texto en linea aparte), alineados y con un tick que muestre que son items (características)
- Sin los tick (u otra solución) me parece que no se entiende que un plan incluye al otro.

Conceptualmente:
- ¿No hay plan de "resaltado de cuadro de búsqueda" o prioridad en la búsqueda? (sería mas barato que todos)
- Lo de turnos múltiples es raro. ¿Se refieren a turnos "recurrentes" o consecutivos?
- No me parece bien poner una descripción tan amplia cuando no la tenemos especificada ni para nosotros mismos. Se pueden obviar palabras para que quede más simple y conciso (hay que leer mucho sino).
- Estaría bueno que se generen cero rebotes de usuarios por llegar a la pantalla y no darse cuenta que si pone siguiente no le cobramos nada. Me parece que sin el plan gratuito incluido en los planes puede llegar a pasar eso y es crítico en este momento del proyecto.

**Comment by tomasgil123** [comment]
Coincido con respecto a lo grafico. Con respecto a lo conceptual:
- No ofrecemos el servicio de publicidad porque todavia el tipo no puede ver la pagina andando ni sabe cuanto trafico tiene. Me parece que es dificil que esa propuesta tenga valor para el tipo en este momento, por eso al final la saque.
- Lo de turnos multiples lo voy a tratar de redactar para que se entienda. La idea es que el alumno pueda reservar, por ejemplo, 5 clases. Vi paginas que no te permiten reservar mas de un turno por alumno.
- El problema que se puede generar sin la descripcion es que el tipo no entienda la propuesta de valor, sobre todo en el segundo plan y con respecto a los SMS.
- Hay que asegurarse que el tipo entienda que lo que le ofrecemos son servicios extra. Voy a re redactar el textito de arriba para no dejar ninguna duda. Si se agrega un plan gratis, habria que mandar el paso al principio.

**Comment by nicogarcia** [comment]
Te contesto en el mismo orden:
- Me parece que todo el mundo conoce lo que es un perfil destacado en una página de búsqueda. Más aún si vienen de avisos offline o plataformas que tienen esa característica.
- No me queda claro lo de los turnos múltiples, ¿sería equivalente a que el alumno saque muchos turnos? No me parece una funcionalidad premium.
- No dije sin la descripción. Dije obviar palabras, hay verbos de más y se hace muy extenso. Ej: "Tus alumnos reciben una notificación antes de cada clase" (no necesariamente es por SMS)
- Si podes "asegurar" eso, puede ser, pero como esta no creo que funcione como esperamos.

**Comment by sergioam90** [comment]
Le planteaba lo mismo al mono, en lo que refiere a que el oferente no se sienta obligado a elegir uno de los dos planes o salir de la página. 

Mi opción era agregar un plan Free con los servicios básicos, formando así 3 columnas

**Comment by tomasgil123** [comment]
Si agregamos el plan free tendriamos que mandar el paso ese al principio. Que te ofrezcan un plan free despues de que completaste todo el proceso de registracion es algo que para mi le va a resultar muy raro al oferente. Eso se ofrece siempre al principio, antes de que tengas que completar nada.

**Comment by sergioam90** [comment]
Sino cambiar el texto para evitar dudas: "Para finalizar, elegí destacar tus anuncios o continuar con el plan standar"

**Comment by sergioam90** [comment]
estandar

**Comment by sergioam90** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10031218/5abf1590-6152-11e5-82be-ffd45a61f90e.jpg)

**Comment by nicogarcia** [comment]
El color del fondo del titulo podría ser mas oscuro y sin los puntos abajo (o cambiarlo por una linea). Sigo insistiendo con el borde de los cuadros, linea mas fina y gris o tarjetas. Subí screenshots de las dos opciones.

**Comment by nicogarcia** [comment]
Creo que hay que aplicarle el estilo de materialize a los planes, ¿no queda mejor?
![image](https://cloud.githubusercontent.com/assets/241306/10054586/4078a938-6208-11e5-9e2e-a3b5c8111415.png)

**Comment by sergioam90** [comment]
Ese es el estilo de materialize?

**Comment by sergioam90** [comment]
Lo veo con colores muy fuertes, tal vez con colores tipo pastel quedaria mejor. Es como si te encandilara

**Comment by nicogarcia** [comment]
Me refería a los bordes, sí, los colores mas claros deben quedar mejor.

**Comment by sergioam90** [comment]
Si, no queda mal la sombra en lugar de los bordes. Yo la había probado antes tambien. Fijate que (no se porque) el div violeta de "Plus" corta la sombra, dando la sensación que esta a la misma altura y no atrás.

**Comment by nicogarcia** [comment]
Hay que acomodarlo eso, no creo que sea complicado.

**Comment by sergioam90** [comment]
Gente, hoy me junte con el mono y pensábamos lo siguiente:

(Primero me despido antes que me maten, fue un gusto conocerlos.)

Ahora si, esto: Nos parece mucho mostrar 7 globos arriba que señalen 7 pasos. Quitemos los dos primeros pasos del proceso (que se muestren igual pero sin que cuenten en los pasos) y unamos algunos como por ejemplo el de selección de materias.

Puede que a la gente no le guste mucho entrar y ver de entrada que tiene que completar 7 pantallas.

**Comment by tomasgil123** [comment]
Paso materias: los check boxes se van a visulizar en dos columnas. En una van a estar los niveles "primario, secundario, terciario, universitario" y en otra los niveles "basico, intermedio y avanzado". Arriba de cada columna apareceria un texto de ayuda; en la primera se mostraria un texto o un tooltip que dice "para materias academicas" y arriba de la segunda columna uno que dice "para materias de idiomas o musica"

**Comment by sergioam90** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10080100/1e3f315e-62c4-11e5-82a4-326e4849bc56.jpg)

**Comment by nicogarcia** [comment]
¡Buenísimo! :smiley:

**Comment by sergioam90** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13783674/10081810/1829d45a-62cd-11e5-953e-389e90a71140.jpg)

**Comment by nicogarcia** [comment]
¡Joya!
