### ISSUE TITLE
Filter description in two lines

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#44]

**Comment by federicojasson** [comment]
¿Qué tal está? ("A domicilio" está más gris porque el cursor está sobre él, aunque no sea vea en la screenshot)

![image](https://cloud.githubusercontent.com/assets/3299231/9802989/cf8dd2c4-57f4-11e5-92ec-452594128f6a.png)

**Comment by nicogarcia** [comment]
Queda bueno como botón, no me convencen las lineas igual, me parece q qda mas cargado. El signo precio, ¿por qué esta en gris? Hay que ver bien lo de responsive.

**Comment by nicogarcia** [comment]
Están en un buen nivel ahora.
