### ISSUE TITLE
Change teacher features and schedule directive

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#47]
Features should include:
- Home lessons
- Individual lessons
- Group lessons
- Teacher degree

For not available features its icon should be muted (in gray).

**Comment by nicogarcia** [comment]
This is the preview for comments above features and schedule:
![image](https://cloud.githubusercontent.com/assets/241306/9746645/9250a504-564f-11e5-83df-9ba03d2acda1.png)

**Comment by nicogarcia** [comment]
Remove titles, space icons of each category and add tooltips.

**Comment by nicogarcia** [comment]
Lighter gray for unavailable

**Comment by federicojasson** [comment]
Idea: More information could be appended to the right of the presentation card (maybe when hovering).

**Comment by nicogarcia** [comment]
Removed titles, spaced icons. Is spacing correct? @tomasgil123 @sergioam90 
![image](https://cloud.githubusercontent.com/assets/241306/9772329/cf18be46-5711-11e5-9471-7453b52e4bcc.png)

**Comment by tomasgil123** [comment]
It would look better if Schedule icons spacing = personal-group class icons spacing

**Comment by nicogarcia** [comment]
What would be the right spacing? Schedule or personal-group? Besides that, my question was if spacing between personal-group and home lesson should be equal to space between home lesson and schedule. What do you think?

**Comment by tomasgil123** [comment]
Lets see how it looks when the space between home lesson icon and schedule icons is equal to the space between personal-group icons and home lesson icon

**Comment by federicojasson** [comment]
¿Qué tal así?
![captura](https://cloud.githubusercontent.com/assets/3299231/9910177/3dd12ade-5c72-11e5-9aae-0380747a09b0.PNG)

**Comment by nicogarcia** [comment]
Muy buena! Con las estrellas mas pegadas arriba y la distancia abajo me parece que quedaría mejor.

**Comment by federicojasson** [comment]
Les dejo algunas fotos

![horizontal no photo](https://cloud.githubusercontent.com/assets/3299231/10064097/6470583e-624b-11e5-9265-97de2b3795e6.PNG)

![vertical no photo](https://cloud.githubusercontent.com/assets/3299231/10064098/6472ddca-624b-11e5-9c2e-a1360b4c9dfa.PNG)

![horizontal photo](https://cloud.githubusercontent.com/assets/3299231/10064099/6473aeee-624b-11e5-82d3-f510649c36a7.PNG)

![vertical photo](https://cloud.githubusercontent.com/assets/3299231/10064100/6475c8a0-624b-11e5-9111-7e8b2668d1dd.PNG)

**Comment by nicogarcia** [comment]
¡Bien! ¡Quedaron muy buenas! Me parece que quedaron medio bajitas las horizontales, los iconos deberían ir mas grandes (supongo que eso me queda a mi).

**Comment by federicojasson** [comment]
La vertical es en realidad cuando se achica la pantalla (celular).
La altura no la cambié (144px), pero podés agrandar los íconos si querés.
Queda bueno el efecto de la vertical cuando no hay foto (fue medio accidental jaja).

**Comment by federicojasson** [comment]
@nicogarcia ya está la directiva y la lista de tareas restantes.

**Comment by nicogarcia** [comment]
Joya

**Comment by federicojasson** [comment]
A continuar en: #100
