### ISSUE TITLE
Implement image uploading with Cloudinary

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-client#48]
Should use the Cloudinary's Angular library:
https://github.com/cloudinary/cloudinary_angular

Also, a preset must be defined to restrict the operation parameters.

**Comment by federicojasson** [comment]
Template:

![image](https://cloud.githubusercontent.com/assets/3299231/10111506/dc13fdc2-63aa-11e5-9649-bcb2f14f789b.png)

**Comment by nicogarcia** [comment]
¡Buenísimo!

**Comment by federicojasson** [comment]
TODOs:
- Fix "same-origin policy" problem
- Add responsive style
- Implement error handling for image deletion

**Comment by federicojasson** [comment]
TODOs added in #154
