### ISSUE TITLE
Use library to load partial CSS files on demand

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-client#65]
Should we use a library to load partial CSS files?

I found this one:
https://github.com/door3/angular-css

It allows us to specify the CSS file as a routing parameter (just like the template URL).

**Comment by nicogarcia** [comment]
Remember that we have all CSS minified and concatenated, so it's one file. I think we should evaluate the loading time of that file and take further action with that information.

**Comment by federicojasson** [comment]
You' re right. Close it
