### ISSUE TITLE
Redesign subject selection

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#66]
Requerimientos:
- Búsqueda real-time con los siguientes criterios:
  - Nombre de la materia:
    - Materias coincidentes
  - Nombre de la categoría:
    - Materias pertenecientes a dicha categoría
    - Categorías coincidentes
- La selección debe mostrarse a parte y ser personalizable.
- Debe haber una distinción visual entre materia y categoría.

Escriban lo que haga falta en los comentarios y lo agrego acá.

**Comment by federicojasson** [comment]
¿Debe permitir multiple y single selection? ¿O sólo multiple?

**Comment by nicogarcia** [comment]
Si, para la landing page simple y múltiple para la página de búsqueda.

**Comment by nicogarcia** [comment]
El subject select se tiene que mostrar en dos columnas, una para "Academicas" y otra para "Idiomas, música", ¿cómo se puede hacer?
