### ISSUE TITLE
Design website logo and add as page favicon

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#70]

**Comment by nicogarcia** [comment]
¿Algo así? Me gusta la idea del pizarrón, el color verde, y podría ser con una U adentro. ¿Qué dicen?

![images](https://cloud.githubusercontent.com/assets/241306/10009748/b61fe6f8-60b7-11e5-856f-83bea6ab45fe.jpg)

**Comment by tomasgil123** [comment]
Puede ser. Por ahi puede armarse como un escudo de equipo de futbol pero que recuerde a un pizarron, con la U adentro. Otra opcion es escribir "Upclaz" como con tiza y que la U o la L tengan una flechita que vaya para arriba

**Comment by nicogarcia** [comment]
Creo que sería bueno que el logo no este muy cargado para que se pueda incrustar en cualquier lado, en este sentido, no debería tener mas de dos letras adentro y debería ser lo mas cuadrado posible. Notar como son los iconos de las páginas, ej Github, Google, Facebook, Drive, etc. Ese icono sería el favicon, y también en algún momento el icono de la aplicación móvil.

**Comment by nicogarcia** [comment]
Para que sea consistente con la página deberíamos tener en cuenta esto: https://www.google.com/design/spec/style/icons.html

**Comment by tomasgil123** [comment]
Es cierto, la mayoria son cuadrados o circulares. Y si la U tiene dos flechitas en las puntas?

**Comment by nicogarcia** [comment]
¿Así? 
![image](https://cloud.githubusercontent.com/assets/241306/10010137/f41bcf30-60bc-11e5-8125-a0589c464bb3.png)

**Comment by tomasgil123** [comment]
Claroo, algo asi.

**Comment by sergioam90** [comment]
![logo](https://cloud.githubusercontent.com/assets/13783674/10088359/b5b41b68-62f0-11e5-98b3-51a734dc81f2.png)

**Comment by sergioam90** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/13783674/10112656/4fc5d85a-63b3-11e5-96d4-3cef1cf748d8.jpg)

**Comment by nicogarcia** [comment]
¡Tremendo! (La sombra esta un poquito rara, ¿en qué te basaste para la forma?)

**Comment by sergioam90** [comment]
Rara en que sentido?

**Comment by federicojasson** [comment]
¡Excelente! La sombra le dio estilo, no sé con qué color me quedo.

**Comment by sergioam90** [comment]
Es la nueva onda de iconos, mira:
![sin titulo-1](https://cloud.githubusercontent.com/assets/13783674/10112730/1ca3f56e-63b4-11e5-92f2-3c71c12330ca.jpg)

**Comment by nicogarcia** [comment]
En la amplitud de la sombra

**Comment by sergioam90** [comment]
Por ahi se puede corregir para que no quede tan en paralelo a la inclinación de la diagonal derecha de la flecha.

**Comment by federicojasson** [comment]
El blanco con letra naranja me cuesta distinguir la U, ¿no les pasa?

**Comment by sergioam90** [comment]
![logo](https://cloud.githubusercontent.com/assets/13783674/10112913/8e3c32bc-63b5-11e5-9dfe-155c29e3e7a4.png)

**Comment by nicogarcia** [comment]
¡Genial!

**Comment by sergioam90** [comment]
![logo](https://cloud.githubusercontent.com/assets/13783674/10112969/35eb5664-63b6-11e5-8b99-a952fb8f4630.png)
