### ISSUE TITLE
Add "beginner", "intermediate" and "advanced" subject levels

### ISSUE THREAD

**Issue by federicojasson** [nicogarcia/classes-web-client#73]

**Comment by tomasgil123** [comment]
Fede, te dejo la lista con las materias aca, por si no la tenias https://docs.google.com/spreadsheets/d/1cifFOKHDhOXRD0swNloeesk38NGS2CHRTIi1FsgWyQI/edit#gid=0 falta agregar las materias relacionadas con musica
