### ISSUE TITLE
flyer design

### ISSUE THREAD

**Issue by sergioam90** [nicogarcia/classes-web-client#75]
Terminemos de pulir asi los podemos mandar a imprimir la semana que viene.

![afiche verano3](https://cloud.githubusercontent.com/assets/13783674/9923739/eece9fe0-5cce-11e5-8f63-6b241cedea36.jpg)
![folleto2](https://cloud.githubusercontent.com/assets/13783674/9923744/f96578fc-5cce-11e5-8252-b51d47c2eb4b.jpg)

**Comment by federicojasson** [comment]
Esta es la última versión que tengo del de Bart

![final-verano](https://cloud.githubusercontent.com/assets/3299231/9924391/5c58678e-5cd5-11e5-9e92-3c9f107c394b.jpg)

**Comment by nicogarcia** [comment]
Estan muy bien! Me gusta más este si la imagen estuviera un poco mas saturada (el color, un poco menos que la otra).
¿Podríamos aprovechar el "Eameo" en lugar de "vieja"? Por la pagina de fb, es conocida la frase.
 " Eameo**,** dame toda' las vacacione'! "

**Comment by tomasgil123** [comment]
Si, me gusta la idea de poner "eameo"

**Comment by federicojasson** [comment]
![final-verano](https://cloud.githubusercontent.com/assets/3299231/9934794/d17a51ea-5d29-11e5-8087-65a17ba95a08.jpg)

**Comment by sergioam90** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/13783674/9950324/cbe210ae-5d8f-11e5-9432-c7a28b469135.jpg)
![Uploading folleto.jpg…]()

**Comment by sergioam90** [comment]
![folleto](https://cloud.githubusercontent.com/assets/13783674/9950329/d6e65ae6-5d8f-11e5-9abb-55e7eaebe6b9.jpg)

**Comment by sergioam90** [comment]
En la 2da imagen, el "piso" es del color del pizarron de la landing page, y la tipografia del url tambien de la página. No me convence del todo, pero para mantener una linea..

**Comment by nicogarcia** [comment]
¿y si hacemos el fondo verde mejor? y el piso, ¿naranja?

**Comment by sergioam90** [comment]
A ver asi...
![afiche verano4](https://cloud.githubusercontent.com/assets/13783674/10002774/6219b800-607f-11e5-9ebc-9befd39d51bc.jpg)
![folleto piso pizarron2](https://cloud.githubusercontent.com/assets/13783674/10002775/6221b866-607f-11e5-836c-3170af79f629.jpg)

**Comment by nicogarcia** [comment]
¡Mucho mejor! Por ahí mejor blanco que gris el piso.

**Comment by sergioam90** [comment]
![folleto piso pizarron2](https://cloud.githubusercontent.com/assets/13783674/10003345/4b4241a8-6082-11e5-8602-81343784ad3d.jpg)

**Comment by tomasgil123** [comment]
mmm No me termina de convencer. Me gusta mas la anterior. Sergio, les agregarias las redes sociales al flyer de materias chorras, para ver como queda? por ahi se pueden poner abajo del nombre de la pagina y arriba de la frase

**Comment by sergioam90** [comment]
Lo pensé, pero me pareció que iba a quedar muy mal en ese lugar que decís vos.

La otra opción es hacer una barra al costado con esa info.

**Comment by sergioam90** [comment]
El dato importante es que los folletos tienen la misma tipografía que la página.

![folleto piso pizarron2](https://cloud.githubusercontent.com/assets/13783674/10003592/7a5eee4a-6083-11e5-975e-9aeff7b2de88.jpg)

**Comment by tomasgil123** [comment]
En una barra al costado no los veo bien a los iconos de las redes sociales. Si achicamos un poco el dibujo, subimos un poco mas para arriba el nombre de la pagina y ahi si probamos ponerlos abajo? que les parece?

**Comment by sergioam90** [comment]
No queda bien..

![afiche verano5](https://cloud.githubusercontent.com/assets/13783674/10003947/6dda9a8c-6085-11e5-8f45-dffc9977cadd.jpg)
![afiche verano6](https://cloud.githubusercontent.com/assets/13783674/10003948/6ddc6f92-6085-11e5-96f2-3e233c81ce6c.jpg)

**Comment by sergioam90** [comment]
Si agregamos una tercera red social puede safar

**Comment by tomasgil123** [comment]
falta instagram, tmb vamos a tener una cuenta ahi

**Comment by sergioam90** [comment]
![afiche verano6](https://cloud.githubusercontent.com/assets/13783674/10004184/cd006e1e-6086-11e5-81a7-ae8e3e2bbd71.jpg)

**Comment by tomasgil123** [comment]
No me termina de convencer ninguna de las anteriores. No se bien que es, pero puede tener que ver con como esta distribuido el texto en el flyer. En el de Bart eso como que no pasa. Si lo hacemos parecido al de Bart? como les parece que quedara?

**Comment by nicogarcia** [comment]
Se le podría bajar el tono al verde, o sea, mas claro como el de la imagen de bart (sin que deje de parecer pizarron)

**Comment by sergioam90** [comment]
Asi, Nico?
![afiche verano6](https://cloud.githubusercontent.com/assets/13783674/10019923/77ad5e6e-6116-11e5-9630-442e0ea5be8a.jpg)

**Comment by nicogarcia** [comment]
Como esto:
![image](https://cloud.githubusercontent.com/assets/241306/10020369/db2c0e16-6118-11e5-8d37-61be0bd07cf1.png)

**Comment by sergioam90** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/13783674/10020787/266cc83c-611b-11e5-96b9-7ae05bb208e9.jpg)

**Comment by tomasgil123** [comment]
Me gusta mas como queda la imagen a la izquierda del flyer, pero la diagonal no me termina de convencer. Si sacamos la diagonal y hacemos coincidir la frase con lo verde y agrandamos el nombre, como quedara?

**Comment by nicogarcia** [comment]
Mucho mejor así. Para mí la diagonal no queda mal y, además, ya la aceptamos. Sigue sin convencerme el verde pero estaría casi lista.

**Comment by sergioam90** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/13783674/10021224/61aa16c8-611d-11e5-8730-a52a80b845d8.jpg)

**Comment by nicogarcia** [comment]
¡Perfecto!

**Comment by sergioam90** [comment]
Hagamos los últimos retoques si es necesario así ya nos preparamos para imprimirlos.

No aparece el logo, pero no encuentro forma de ponerlo y tampoco me parece que sea tan importante en esta primera tanda.

Estos son los finales por ahora:

![folleto pizarron 2](https://cloud.githubusercontent.com/assets/13783674/10124384/81324cca-652a-11e5-8cea-8f9c622c4961.jpg)
![24b5827abd1378176b1ecaa037fb050b](https://cloud.githubusercontent.com/assets/13783674/10124385/813678f4-652a-11e5-9372-0f2751f284c8.jpg)

**Comment by nicogarcia** [comment]
Para mí estan bien así.
