### ISSUE TITLE
Design signup steps bar directive

### ISSUE THREAD

**Issue by nicogarcia** [nicogarcia/classes-web-client#76]
Debe recibir:
- Cantidad de pasos
- Paso actual
- Títulos de los pasos
- Pasos activables manualmente (los pasos internos de teacher se pueden navegar, pero los demás en su mayoría NO)

Idea:
```
  steps: [
    clickable: false,
    number: , (?) // may be get by array index
    title: "Paso 1"
  ]
```

Hay un servicio implementado que guarda el paso actual, se podrían definir ahí los pasos para teacher y student respectivamente.

![image](https://cloud.githubusercontent.com/assets/241306/9964747/5f240156-5e08-11e5-8727-8818975941e5.png)

http://www.jquery-steps.com/Examples

**Comment by federicojasson** [comment]
Creo que es mejor que reciba los pasos en una única estructura (array).
Con length obtenés la cantidad de total, con index el número de paso.

Para cada paso entonces bastaría con guardar "title" y "clickable".

**Comment by nicogarcia** [comment]
Claro, es lo q puse, me faltaron los {} en el arreglo de steps

**Comment by federicojasson** [comment]
Ahhhh, pensé que era el scope. Perfecto entonces.

**Comment by federicojasson** [comment]
¿Esto debe verse horizontalmente o verticalmente?

**Comment by nicogarcia** [comment]
¿Ambas? Podes hacerlo con columnas y ng-class quizá. Deberíamos definir si se puede hacer login desde el cel. @tomasgil123 (no nos olvidemos que el login va a ser el mismo después de lanzar y es el mismo para estudiantes)

**Comment by tomasgil123** [comment]
El tema es que la manera en la que pensamos contactar los early adopters es mediante llamados telefonicos. Si al tipo la idea le gusta, es de suponer que entre a la pagina desde su cel e intente registrase. Corremos el riesgo de que todo el proceso lo fastidie, no lo termine y despues se olvide. Sin embago, ya vamos a tener su mail como para volver a contactarlo por ese medio.
Otra opcion es que no pueda registrarse desde el cel. Ahi el riesgo que corremos es que el tipo se olvide de la pagina y nunca se registre. La unica manera de volver a contactarlo es llamandolo.
Una cosa que se puede hacer es que, habiendose registrado, se le recomiende seguir con el prceso de registracion desde una pc. Que opinas @sergioam90 ?

**Comment by nicogarcia** [comment]
@federicojasson 
Faltaría agregar una feature:
- Hacer una diferencia visual en los pasos anteriores al actual para indicar que ya fueron completados.

**Comment by nicogarcia** [comment]
Y se podría achicar un poco el tamaño de los círculos

**Comment by nicogarcia** [comment]
Estaría bueno que 'clickable' no cambie el aspecto visual del elemento por ahora (es complicado hacer click y que te lleve al link correspondiente, los dos tendriamos que implementarlo)

**Comment by nicogarcia** [comment]
Creo que hay que aplicarle el estilo de materialize a los planes, ¿no queda mejor?
![image](https://cloud.githubusercontent.com/assets/241306/10054488/a3977374-6207-11e5-9c83-f7ec087fcd19.png)
