### ISSUE TITLE
step 1 and 2 - early adopters

### ISSUE THREAD

**Issue by sergioam90** [nicogarcia/classes-web-client#77]
![2](https://cloud.githubusercontent.com/assets/13783674/9978633/80566aac-5f12-11e5-8f4e-fa46eca15adf.jpg)
![1](https://cloud.githubusercontent.com/assets/13783674/9978634/805a680a-5f12-11e5-91c1-27cdcf3438a3.jpg)

**Comment by nicogarcia** [comment]
Buenísimo! Lo del mail tiene que ser botón me parece, lo llena en el paso siguiente al mail (se puede poner primero, no se si conviene intentar implementar lo del registro incompleto) @tomasgil123 @federicojasson

**Comment by tomasgil123** [comment]
Si yo quiero registrarme usando mi mail, como seria el preceso? tengo que apretar el boton de "mail" y luego completar mail y contraseña en la parte de datos del usuario? Me parece que es mejor que complete su mail y contraseña ahi, porque de irse en el siguiente paso no tenemos como contactarlo. Aparte, se le van a acumular varias cosas para completar en un solo paso.
