### ISSUE TITLE
Usability testing early adopters

### ISSUE THREAD

**Issue by tomasgil123** [nicogarcia/classes-web-client#88]
Consistira en que un numero de users (entre 5 y 10) completen el proceso de registracion y luego completen la siguiente encuesta online:
Los objetivos generales son conseguir feedback sobre las dificultades que enfrento en el proceso de registracion en general, pero sobre todo al momento de elegir las materias; y si se entendio bien como va a funcionar la pagina. 

- A que paginas web consideras que se parece upclaz.com? (marca todas las paginas que te parezcan similares)

Facebook - Mercado libre - OLX - Alamaula - Netflix - Twitter - Spotify - ninguna de las anteriores

- Pudiste encontrar todas las materias que querias dar?

- Cuales son las materias que te gustaria dar que no pudiste encontrar en el listado de materias?

- Indica con un numero del 1 al 5, siendo 1 "muy bajo" y 5 "muy alto", el grado de dificultad tuvo para vos el proceso de seleccion de las materias que querias dar

1 - 2 - 3- 4- 5   

- Que cosas cambiarias para hacer mas sencillo el proceso de seleccion de las materias?

- Indica con un numero del 1 al 5, siendo 1 "muy bajo" y 5 "muy alto", el grado de dificultad tuvo para vos el proceso de hacerte una cuenta en terminos generales

1 - 2 - 3- 4- 5   

- Que cosas cambiarias para hacer mas sencillo el proceso de hacer una cuenta?

- Hay algun dato que hubieses preferido no dar?

Edad - Genero - Direccion - Nivel de estudios - Numero de telefono - otro

**Comment by tomasgil123** [comment]
Les parece agregar algo mas o instrumentarlo de manera diferente? @nicogarcia @federicojasson @sergioam90

**Comment by nicogarcia** [comment]
Me parece bien, ¿cómo les haces llegar la encuesta?

**Comment by tomasgil123** [comment]
Tengo una lista de 5 conocidos que se que dieron clases, o dan, o que les interesaria dar. Pensaba contactarlos, pedirles que se registren y luego mandarles la encuesta online (seria un formulario de google). Es posible borrar los datos de alguno o todos los usuarios que se registren en esta etapa?

**Comment by nicogarcia** [comment]
Supongo que si.

**Comment by tomasgil123** [comment]
https://docs.google.com/forms/d/1BYrABlU9JJY89RV3Y_w6UKfALf--XXjEQ1IYgkYQRwo/edit# encuesta terminada
